#!/usr/bin/env bash
# check-lesson-parity.sh
# Verifies that the set of lesson files on disk, the lesson keys in progress.json,
# and the lesson maps in CLAUDE.md / AGENTS.md all agree.
#
# Catches:
# - lesson files added but not registered in progress.json or the lesson maps
# - lesson IDs registered but missing on disk
# - typos in lesson filenames
# - drift between CLAUDE.md and AGENTS.md lesson orders
#
# Exit code: 0 if everything agrees, 1 if any mismatch is found.

set -e

# Force C locale so that `sort`, `comm`, and Python's str-sort agree on byte
# ordering. Without this, mixing them produces phantom diffs.
export LC_ALL=C

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

# Detect Python 3 — same logic as setup.sh. Some environments (Windows,
# Conda) ship Python 3 as `python` rather than `python3`.
PYTHON=""
if command -v python3 &>/dev/null; then
  PYTHON=python3
elif command -v python &>/dev/null && python --version 2>&1 | grep -q "Python 3"; then
  PYTHON=python
else
  echo "✗ No Python 3 found on PATH (tried `python3` and `python`)" >&2
  echo "  Install Python 3 from https://python.org/downloads and re-run." >&2
  exit 1
fi

FAIL=0
fail() { echo "  ✗ $1" >&2; FAIL=1; }
pass() { echo "  ✓ $1"; }

echo "Lesson parity check"
echo "==================="

# ── 1. Build the set of lesson IDs from files on disk ──────────────
# Lesson files match: module-X/X-Y[a-z]?-<slug>.md
DISK_IDS=$(find module-* -name '[0-9]*.md' \
  | sed -E 's|module-[0-9]+/([0-9]+-[0-9]+[a-z]?)-.*\.md|\1|' \
  | sort -u)
DISK_COUNT=$(echo "$DISK_IDS" | grep -c .)
echo ""
echo "Found $DISK_COUNT lesson files on disk"

# Helper: extract lesson IDs from a file. Uses Python for portable regex
# (Git Bash on Windows can't use grep -P reliably due to locale issues).
# Lookbehind/lookahead rule out two known false-positive patterns:
#   - model names like `claude-sonnet-4-6` (preceded by `-`)
#   - brace-expansion shorthand like `10-2{a,b,c}` (followed by `{`)
# A real lesson ID is never preceded by alpha or `-`, and never followed by
# alpha, digit, or `{`.
extract_ids() {
  local file="$1"
  # `sys.stdout.reconfigure(newline='')` prevents Python on Windows from
  # translating \n to \r\n, which would break `comm` against bash-tool output.
  "$PYTHON" -c "
import re, sys
sys.stdout.reconfigure(newline='')
text = open(sys.argv[1], encoding='utf-8').read()
ids = sorted(set(re.findall(r'(?<![a-zA-Z\-])\d+-\d+[a-z]?(?![a-zA-Z0-9{])', text)))
sys.stdout.write('\n'.join(ids) + '\n')
" "$file"
}

# ── 2. Build the set of lesson IDs from progress.json (optional — gitignored, only present after setup.sh) ──
if [ -f progress.json ]; then
  PROGRESS_IDS=$("$PYTHON" -c "
import json, re, sys
sys.stdout.reconfigure(newline='')
with open('progress.json') as f:
    data = json.load(f)
for path in data.get('lessons', {}):
    m = re.search(r'(\d+-\d+[a-z]?)', path)
    if m:
        sys.stdout.write(m.group(1) + '\n')
" | sort -u)
  PROGRESS_COUNT=$(echo "$PROGRESS_IDS" | grep -c .)
  echo "Found $PROGRESS_COUNT lesson IDs in progress.json"

  ON_DISK_NOT_IN_PROGRESS=$(comm -23 <(echo "$DISK_IDS") <(echo "$PROGRESS_IDS"))
  IN_PROGRESS_NOT_ON_DISK=$(comm -13 <(echo "$DISK_IDS") <(echo "$PROGRESS_IDS"))

  if [ -z "$ON_DISK_NOT_IN_PROGRESS" ] && [ -z "$IN_PROGRESS_NOT_ON_DISK" ]; then
    pass "progress.json matches disk ($DISK_COUNT lessons)"
  else
    fail "progress.json out of sync with disk"
    [ -n "$ON_DISK_NOT_IN_PROGRESS" ] && echo "    On disk but not in progress.json:" && echo "$ON_DISK_NOT_IN_PROGRESS" | sed 's/^/      /'
    [ -n "$IN_PROGRESS_NOT_ON_DISK" ] && echo "    In progress.json but not on disk:" && echo "$IN_PROGRESS_NOT_ON_DISK" | sed 's/^/      /'
  fi
else
  echo "  ○ progress.json not present (gitignored — only generated by setup.sh); skipping"
fi

# ── 3. Cross-check the JSON template baked into setup.sh ───────────
# setup.sh contains a HEREDOC with the canonical progress.json shape used at
# first-time setup. If a lesson is added on disk but the setup template isn't
# updated, every new student will see a stale ledger.
SETUP_IDS=$(awk '/cat > progress.json << .JSON/,/^JSON$/' setup.sh \
  | grep -oE '"module-[0-9]+/[0-9]+-[0-9]+[a-z]?-[^"]+\.md"' \
  | sed -E 's|"module-[0-9]+/([0-9]+-[0-9]+[a-z]?)-.*|\1|' \
  | sort -u)
if [ -n "$SETUP_IDS" ]; then
  SETUP_COUNT=$(echo "$SETUP_IDS" | grep -c .)
  echo "Found $SETUP_COUNT lesson IDs in setup.sh progress.json template"
  ON_DISK_NOT_IN_SETUP=$(comm -23 <(echo "$DISK_IDS") <(echo "$SETUP_IDS"))
  IN_SETUP_NOT_ON_DISK=$(comm -13 <(echo "$DISK_IDS") <(echo "$SETUP_IDS"))
  if [ -z "$ON_DISK_NOT_IN_SETUP" ] && [ -z "$IN_SETUP_NOT_ON_DISK" ]; then
    pass "setup.sh progress.json template matches disk"
  else
    fail "setup.sh progress.json template out of sync with disk"
    [ -n "$ON_DISK_NOT_IN_SETUP" ] && echo "    On disk but not in setup.sh template:" && echo "$ON_DISK_NOT_IN_SETUP" | sed 's/^/      /'
    [ -n "$IN_SETUP_NOT_ON_DISK" ] && echo "    In setup.sh template but not on disk:" && echo "$IN_SETUP_NOT_ON_DISK" | sed 's/^/      /'
  fi
fi

# ── 4. Build the set of lesson IDs from AGENTS.md lesson order ─────
# The lesson order line in AGENTS.md looks like:
#   `0-1, 0-2, ..., 10-5`
# extract_ids() strips brace-expansion shorthand like `10-2{a,b,c}` first.
AGENTS_IDS=$(extract_ids AGENTS.md)
AGENTS_COUNT=$(echo "$AGENTS_IDS" | grep -c .)
echo "Found $AGENTS_COUNT lesson IDs in AGENTS.md"

ON_DISK_NOT_IN_AGENTS=$(comm -23 <(echo "$DISK_IDS") <(echo "$AGENTS_IDS"))
IN_AGENTS_NOT_ON_DISK=$(comm -13 <(echo "$DISK_IDS") <(echo "$AGENTS_IDS"))

if [ -z "$ON_DISK_NOT_IN_AGENTS" ] && [ -z "$IN_AGENTS_NOT_ON_DISK" ]; then
  pass "AGENTS.md lesson order matches disk"
else
  fail "AGENTS.md lesson order out of sync with disk"
  [ -n "$ON_DISK_NOT_IN_AGENTS" ] && echo "    On disk but not in AGENTS.md:" && echo "$ON_DISK_NOT_IN_AGENTS" | sed 's/^/      /'
  [ -n "$IN_AGENTS_NOT_ON_DISK" ] && echo "    In AGENTS.md but not on disk:" && echo "$IN_AGENTS_NOT_ON_DISK" | sed 's/^/      /'
fi

# ── 5. Build the set of lesson IDs from CLAUDE.md lesson map ───────
# The CLAUDE.md map has lines like:
#   - `0-1` → `module-0/0-1-install-and-setup.md`
CLAUDE_IDS=$(extract_ids CLAUDE.md)
CLAUDE_COUNT=$(echo "$CLAUDE_IDS" | grep -c .)
echo "Found $CLAUDE_COUNT lesson IDs in CLAUDE.md"

ON_DISK_NOT_IN_CLAUDE=$(comm -23 <(echo "$DISK_IDS") <(echo "$CLAUDE_IDS"))
IN_CLAUDE_NOT_ON_DISK=$(comm -13 <(echo "$DISK_IDS") <(echo "$CLAUDE_IDS"))

if [ -z "$ON_DISK_NOT_IN_CLAUDE" ] && [ -z "$IN_CLAUDE_NOT_ON_DISK" ]; then
  pass "CLAUDE.md lesson map matches disk"
else
  fail "CLAUDE.md lesson map out of sync with disk"
  [ -n "$ON_DISK_NOT_IN_CLAUDE" ] && echo "    On disk but not in CLAUDE.md:" && echo "$ON_DISK_NOT_IN_CLAUDE" | sed 's/^/      /'
  [ -n "$IN_CLAUDE_NOT_ON_DISK" ] && echo "    In CLAUDE.md but not on disk:" && echo "$IN_CLAUDE_NOT_ON_DISK" | sed 's/^/      /'
fi

# ── 6. Verify the X / N total in CLAUDE.md /progress matches reality ──
EXPECTED_TOTAL="$DISK_COUNT"
CLAUDE_TOTAL=$(grep -oE 'X / [0-9]+ complete' CLAUDE.md | grep -oE '[0-9]+' | head -1)
if [ "$CLAUDE_TOTAL" = "$EXPECTED_TOTAL" ]; then
  pass "CLAUDE.md /progress total ($CLAUDE_TOTAL) matches disk ($EXPECTED_TOTAL)"
else
  fail "CLAUDE.md /progress total ($CLAUDE_TOTAL) does not match disk ($EXPECTED_TOTAL)"
fi

echo ""
if [ "$FAIL" -eq 0 ]; then
  echo "✅ All lesson parity checks passed"
  exit 0
else
  echo "❌ Lesson parity checks failed"
  exit 1
fi
